import { ReactElement, ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import DarkModeButton from '@/components/DarkModeButton/dark-mode-button.component'
import ReduxProvider from '@/providers/redux-provider/redux-provider'
import ThemeProvider from '@/providers/theme-provider/theme-provider'

import '@/app/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}): ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ThemeProvider>
            <h1 className="text-4xl w-full bg-blue-700 p-3 flex justify-center">
              Header App
            </h1>
            {children}
            <DarkModeButton />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
